version: '3.8'

services:
  web:
    image: rachev/petstagram2023_1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./env/.env
    volumes:
      - /tmp/app-resources/staticfiles:/app/staticfiles
    platform: linux/amd64
    command: gunicorn --bind=0.0.0.0:8000 Petstagram23.wsgi:application
    links:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
        POSTGRES_DB: petstagram23_db3
        POSTGRES_USER: postgres-user
        POSTGRES_PASSWORD: password
        PGDATA: /var/lib/postgresql/data/pgdata
    env_file:
      - ./env/.env
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  nginx:
    image: nginx
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - /tmp/app-resources/static:/home/app/web/staticfiles
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    links:
      - web